import type { PRDescriptionContext, PRClient } from './types';
import { createGitHubClient } from './github';
import { createGitLabClient } from './gitlab';

export function generatePRDescription(ctx: PRDescriptionContext): string {
  const lines: string[] = [];

  lines.push(`## ${ctx.taskTitle}`);
  lines.push('');

  if (ctx.trackId) {
    lines.push(`**Track:** ${ctx.trackId}`);
  }
  lines.push(`**Task:** ${ctx.taskId}`);
  if (ctx.commitHash) {
    lines.push(`**Commit:** \`${ctx.commitHash.slice(0, 8)}\``);
  }
  lines.push('');

  if (ctx.specSummary) {
    lines.push('## Summary');
    lines.push('');
    lines.push(ctx.specSummary);
    lines.push('');
  }

  if (ctx.agentSummary) {
    lines.push('## Agent Output');
    lines.push('');
    lines.push(ctx.agentSummary);
    lines.push('');
  }

  if (ctx.acceptanceCriteria && ctx.acceptanceCriteria.length > 0) {
    lines.push('## Acceptance Criteria');
    lines.push('');
    for (const criterion of ctx.acceptanceCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by Fleet Commander | Task ${ctx.taskId}`);

  return lines.join('\n');
}

export type Provider = 'github' | 'gitlab';

export function createPRClient(provider: Provider, cwd: string): PRClient {
  switch (provider) {
    case 'github':
      return createGitHubClient(cwd);
    case 'gitlab':
      return createGitLabClient(cwd);
    default:
      throw new Error(`Unknown PR provider: ${provider}`);
  }
}
