/**
 * Re-export barrel for backward compatibility.
 * All hooks and types are now split into domain files under ./convex-realtime/.
 * New code should import from '@/lib/convex-realtime' directly.
 */
export {
  useFleetStatus,
  useBlockedTasks,
  useOpenIssues,
  useActiveRuns,
  useAlerts,
  useUnresolvedCriticalCount,
  useDashboardData,
  useActiveAlerts,
  useCircuitBreakers,
  useInProgressTasks,
  useReadyTasks,
  useActiveEmployees,
  useCompletionTrends,
  useAgentUtilization,
  useBottlenecks,
  useQueueDepth,
  useHookMetrics,
  useSessionMetrics,
  usePhaseBreakdown,
  usePhaseTrends,
  useAgentLatencyStats,
  useSlowAgents,
  useRegressionAlerts,
  usePerformanceOverview,
  useCostByProject,
  useCostByAgent,
  useCostTrend,
  useSessionSavings,
  useCostPerTask,
  useAnalyticsOverview,
  useCostOverview,
  useSprintBoard,
  useActiveSprint,
  useSprintsByProject,
  useBacklogTasks,
  useAgentsForPlanning,
  useProjectStats,
  useSprintsList,
  useSprint,
  useAgentLeaderboard,
  useAgentPerformanceHistory,
  type AnalyticsArgs,
  type ProjectSlugArgs,
  type LeaderboardEntry,
  type AgentPerformanceHistory,
} from './convex-realtime'
