/**
 * Re-export barrel for backward compatibility.
 * All hooks and types are now split into domain files under ./convex-data/.
 * New code should import from '@/lib/convex-data' directly.
 */
export {
  useConvexQuery,
  useConvexQueryState,
  convexCoverageRecordToDisplay,
  parseToolsJson,
  convexProjectToSummary,
  convexAgentToRecord,
  convexHarnessToRecord,
  useConvexProjectsTransformed,
  useConvexAgentsTransformed,
  useConvexHarnessesTransformed,
  useConvexTasks,
  useConvexIssues,
  useConvexLogs,
  useCoverageHistory,
  useLatestCoverage,
  useFleetHealth,
  useQueueHealth,
  useDispatchTimeline,
  useGovernanceEvents,
  useAnalysisByExecution,
  useAnalysisByProject,
  useAnalysisHistory,
  useSprintHistoryQuery,
  useAgentHistoryQuery,
  useTaskHistoryQuery,
  useAuditEvents,
  useAuditEventsState,
  useReconciliationEvents,
  useReconciliationProposals,
  useReconciliationProposalsState,
  usePolicyWeights,
  useSprintAggregateData,
  useSprintCostTrend,
  useSprintRejectionReasons,
  type CoverageDisplay,
  type DispatchPolicyStatEntry,
  type HarnessReliabilityStatEntry,
  type DispatchTimelineEntry,
  type GovernanceEventEntry,
  type AnalysisResultEntry,
  type AnalysisHistoryEntry,
  type AuditEventEntry,
  type ReconciliationEventEntry,
  type ReconciliationProposalEntry,
  type PolicyWeightsEntry,
  type SprintAggregateData,
  type CostTrendEntry,
  type RejectionReasonEntry,
  type ConvexQueryState,
} from './convex-data'
